#!/bin/bash

if [ -z "$2" ]; then
    COMMAND="cd"
    DIR=$1
else
    COMMAND=$1
    DIR=$2
fi

function go_to_dir {
    if [ -d "$DIR" ]; then
        cd "$DIR"
        if [ -d ".kit" ]; then
            if [ -d "$DIR" ]; then
                cd "$DIR"
            elif [ -d "kcegc" ]; then
                cd kcegc
            elif [ -d "kcl" ]; then
                cd kcl
            else
                ls
            fi
        fi
    else
        if [ $(pwd) == $HOME ]; then
            echo " TOK: No workspaces found"
            cd ~/
        else
            cd ..
            go_to_dir
        fi
    fi
}

if [ "$COMMAND" == "cd" ]; then
    go_to_dir
fi

