#! /usr/bin/python
import sys

def cs(x, pip="*"):
    text = pip
    pos = int(x)
    z = 2
    while len(text) + 2 < int(x):
        if pos - len(text) < 2:
            z = 3
        c = len(str(len(text) + z))
        text = "{}{}".format(text, len(text) + c + 1)
        text = "{}{}".format(text, pip)
        pos = pos - 1
    print text


if __name__ == "__main__":
    if (len(sys.argv) > 2):
        cs(sys.argv[1], sys.argv[2])
    else:
        cs(sys.argv[1])

