#!/bin/bash
echo "┌─────┬────────────────────────────────────────────────────────┐"
echo "│hours│ commits                                                │"
echo "├─────┼────────────────────────────────────────────────────────┤"
git log --author="$1" --date=iso | perl -nalE 'if (/^Date:\s+[\d-]{10}\s(\d{2})/) { say $1+0 }' | sort | uniq -c|perl -MList::Util=max -nalE '$h{$F[1]} = $F[0]; }{ $m = max values %h; foreach (0..23) { $h{$_} = 0 if not exists $h{$_} } foreach (sort {$a <=> $b } keys %h) { say sprintf "│ %02d  │ %4d %s%s│", $_, $h{$_}, "█"x ($h{$_} / $m * 50), " "x (50 - ($h{$_} / $m * 50) + 0.99); }'
echo "└─────┴────────────────────────────────────────────────────────┘"
echo "┌─────┬────────────────────────────────────────────────────────┐"
echo "│ day │ commits                                                │"
echo "├─────┼────────────────────────────────────────────────────────┤"
git log --author="$1" | grep '^Date:' | sort | uniq -c | awk -F' ' '{ print $3 }' | uniq -c | perl -MList::Util=max -nalE '$h{$F[1]} = $F[0]; }{ $m = max values %h; foreach (Mon, Tue, Wed, Thu, Fri, Sat, Sun) { $h{$_} = 0 if not exists $h{$_} } foreach (Mon, Tue, Wed, Thu, Fri, Sat, Sun) { say sprintf "│ %s │ %4d %s%s│", $_, $h{$_}, "█"x ($h{$_} / $m * 50), " "x (50 - ($h{$_} / $m * 50) + 0.99); }'
echo "└─────┴────────────────────────────────────────────────────────┘"

