#!/bin/bash
rm -rf /tmp/chart
DAYS=31
if [ ! -z $1 ]; then
    DAYS=$1
fi

for ((d=1; d<=$DAYS; d++)); do
   echo $((100-$(git log --before="$d day ago" -n 100 --format='%s' | grep 'squash\|fixup\|\.$\|.\{50\}' -c))) >> /tmp/chart
done
chart.py $(cat /tmp/chart)
